config/routes.rb
Rails.application.routes.draw do
  resources :videos do 
    member do 
      patch "stars"
    end
  end
  root to: "videos#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :video
end

app/models/video.rb
class Video < ApplicationRecord
  has_many :notes
  def self.notes
    joins("left join notes on notes.video_id = videos.id").group("videos.id").select('videos.*, avg(notes.note) nbstars').order("avg(notes.note) desc")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: %i[ show edit update destroy stars ]

  # GET /videos or /videos.json
  def index
    Dir.glob(Rails.root.to_s+"/public/**/**.MOV").each do |h|
      @x=Video.find_or_create_by(filename: h.split("/").last)
    end
    @videos = Video.all.notes
  end
  def stars

    (1..5).each{|x| params["#{x}.x"] ? @x = x : nil}
    @y=@video.notes.create!(note: @x, comment: params[:comment])
    redirect_to videos_path
  end

  # GET /videos/1 or /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos or /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to video_url(@video), notice: "Video was successfully created." }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1 or /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to video_url(@video), notice: "Video was successfully updated." }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1 or /videos/1.json
  def destroy
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url, notice: "Video was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:filename, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naturetrek</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
        <% video.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :filename %>
    <%= form.text_field :filename %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Videos Nature Trek</h1>

<table>
  <thead>
    <tr>
      <th>Note moyenne</th>
      <th>Video</th>
      <th colspan="3">Noter cette vidéo</th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%=video.nbstars%>/5</td>
        <td><video controls width=200 height=200 src="/photos/<%=video.filename%>" type="video/mov">
  <p>Votre navigateur ne prend pas en charge les vidéos HTML5.
  Voici <a href="/photos/<%=video.filename%>">un lien pour télécharger la vidéo</a>.</p>
</video>
</td>
<td><%=form_with model: video,url: stars_video_path(video.id) do |form|%>
  <%=text_area_tag :comment,"", placeholder: "commentez ici"%>
  <input type="image" alt="note" name="1" id="image1" src="/assets/mypic.png"/>
  <input type="image" alt="note" name="2" id="image2" src="/assets/mypic.png"/>
  <input type="image" alt="note" name="3" id="image3" src="/assets/mypic.png"/>
  <input type="image" alt="note" name="4" id="image4" src="/assets/mypic.png"/>
  <input type="image" alt="note" name="5" id="image5" src="/assets/mypic.png"/>

<%end%>
  </td>
        <td><%= link_to 'Voir tous les commentaires', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<video controls width=200 height=200 src="/photos/<%=@video.filename%>" type="video/mov">
  <p>Votre navigateur ne prend pas en charge les vidéos HTML5.
  Voici <a href="/photos/<%=@video.filename%>">un lien pour télécharger la vidéo</a>.</p>
</video>
<%if @video.notes.length > 0%>
  <p>notes sur cette vidéo :</p>
  <ul>
<%@video.notes.each do |n|%>
  <li><%=n.note%>/5

  <%if n.comment.length > 0%>
    <%=n.comment%>
  <%else%>
    (pas de commentaire)
    <%end%>

  </li>
  <%end%>
  </ul>
<%else%>
  <p>aucune note sur cette vidéo</p>
<%end%>

<%= link_to 'Retour à toutes les vidéos', videos_path %>